version: "3.7"
services:
  app:
    build:
      args:
        user: tuannh
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tiktok-app
    container_name: tiktok-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tiktok

  db:
    image: mysql:5.7
    container_name: tiktok-db
    restart: unless-stopped
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - tiktok

  nginx:
    image: nginx:alpine
    container_name: tiktok-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tiktok

networks:
  tiktok:
    driver: bridge