export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_LIST_COMMENT = 'GET_LIST_COMMENT';
export const SET_LIST_COMMENT = 'SET_LIST_COMMENT';
export const DELETE_COMMENT   = 'DELETE_COMMENT';
export const SET_LIST_COMMENT_DELETED = 'SET_LIST_COMMENT_DELETED';