export const GET_ALL_ROOM = 'GET_ALL_ROOM';
export const SET_ALL_ROOM = 'SET_ALL_ROOM';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const SET_ALL_MESSAGES = 'SET_ALL_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_ALL_MESSAGES_AFTER_SEND = 'SET_ALL_MESSAGES_AFTER_SEND';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const SET_MESSAGES_AFTER_DELETE = 'SET_MESSAGES_AFTER_DELETE';
